# GENERATED by `fog tf-init`. Keep local-only; regenerate instead of editing.
# WARNING: This override intentionally uses a local backend and test credentials.
# Do not combine it with a real remote backend or production AWS account.

terraform {
  required_version = ">= 1.6.0"

  backend "local" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "__TF_PROVIDER_AWS_VERSION__"
    }
  }
}

provider "aws" {
  region                      = "__AWS_REGION__"
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {
    s3  = "__AWS_ENDPOINT_URL__"
    sqs = "__AWS_ENDPOINT_URL__"
    iam = "__AWS_ENDPOINT_URL__"
    sts = "__AWS_ENDPOINT_URL__"
    rds = "__AWS_ENDPOINT_URL__"
    eks = "__AWS_ENDPOINT_URL__"
  }
}
