apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClassName | quote }}
  labels:
    app.kubernetes.io/managed-by: fogstack
spec:
  controllerName: {{ .Values.controllerName | quote }}
